version: 2
updates:
    - package-ecosystem: "cargo"
      directory: "/blur"
      schedule:
          interval: "daily"
    - package-ecosystem: "cargo"
      directory: "/intake"
      schedule:
          interval: "daily"
    - package-ecosystem: "cargo"
      directory: "/nomnom"
      schedule:
          interval: "daily"
